#!/usr/bin/env python3
"""Generate local deployment assets from a private site list."""
import argparse
import re
from pathlib import Path
from urllib.parse import urlsplit


def read_sites(sites_file):
    sites = set()
    for line in sites_file.read_text().splitlines():
        host = line.split('#', 1)[0].strip().lower()
        if not host:
            continue
        labels = host.split('.')
        if (len(host) > 253 or len(labels) < 2 or labels[-1].isdigit()
                or any(not re.fullmatch(r'[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?', label)
                       for label in labels)):
            raise ValueError('The site list must contain DNS hostnames, one per line')
        sites.add(host)
    return sites


def authentication_enabled(root):
    env = root / 'deploy/.env'
    if not env.exists():
        return False
    for line in env.read_text().splitlines():
        name, _, value = line.partition('=')
        if name.strip() == 'READER_AUTH_ENABLED':
            return value.split('#', 1)[0].strip().strip('\'"') == 'true'
    return False


def ruleset(root):
    """Private site adapters first, since Ladder uses the first matching rule."""
    default = (root / 'deploy/rules.default.yaml').read_text()
    adapters = root / 'deploy/adapters.yaml'
    if not adapters.exists():
        return default
    text = adapters.read_text()
    for line in text.splitlines():
        content = line.split('#', 1)[0].rstrip()
        if content and not (content.startswith('- ') or content.startswith(' ')):
            raise ValueError('deploy/adapters.yaml must be a YAML list of Ladder rules')
        if re.search(r'''domains?:\s*(?:\[\s*)?(['"])\1''', content):
            raise ValueError('deploy/adapters.yaml must name its sites; the catch-all rule is already applied last')
    return '# Generated by tools/configure.py from deploy/adapters.yaml and deploy/rules.default.yaml.\n' + text.rstrip() + '\n\n' + default


def configure(origin, sites_file, root, open_fetch=False):
    u = urlsplit(origin)
    if (u.scheme != 'https' or not u.hostname or u.username or u.password
            or u.query or u.fragment or u.path not in ('', '/')
            or not re.fullmatch(r'[A-Za-z0-9.:-]+', u.netloc)):
        raise ValueError('Use an HTTPS hostname or IPv4 origin without credentials or a path')
    u.port  # Reject malformed or out-of-range ports.
    sites = read_sites(sites_file) if sites_file else set()
    if open_fetch:
        if not authentication_enabled(root):
            raise ValueError('Open fetching requires READER_AUTH_ENABLED=true in deploy/.env')
    elif not sites:
        raise ValueError('Provide at least one site, or use --open with authentication enabled')
    allowed = set()
    for site in sorted(sites):
        aliases = [] if site.startswith('www.') else ['www.' + site]
        allowed.update([site, *aliases])
    rules = ruleset(root)
    # Ladder allows every host when ALLOWED_DOMAINS is empty; Squid still blocks
    # private addresses. The gateway refuses open fetching without a login.
    (root / 'deploy/sites.env').write_text(
        'ALLOWED_DOMAINS=' + ('' if open_fetch else ','.join(sorted(allowed))) + '\n'
        + 'READER_OPEN_FETCH=' + ('true' if open_fetch else 'false') + '\n')
    (root / 'deploy/rules.yaml').write_text(rules)
    script = (root / 'userscript/recssitate.user.js').read_text()
    (root / 'web/recssitate.user.js').write_text(script.replace('__PAGE_RESCUE_ORIGIN__', f'https://{u.netloc}'))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--origin', required=True)
    parser.add_argument('--sites', type=Path, help='private list of known sites; required unless --open')
    parser.add_argument('--open', action='store_true',
                        help='fetch any public host with the generic rule; requires authentication')
    args = parser.parse_args()
    try:
        configure(args.origin, args.sites, Path(__file__).resolve().parent.parent, args.open)
    except ValueError as error:
        parser.error(str(error))
    print('Generated local allowlist, ruleset and userscript; these files are excluded from Git.')
